import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Button } from '@material-ui/core';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Let&apos;s get you a <a>place to eat</a>
        </h1>
        <div className={styles.queryButton}>
          <Link href="/query" passHref>
            <Button variant="contained" color="primary">
              Let's begin
            </Button>
          </Link>
        </div>

{/* 
        <div className={styles.grid}>

        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/geomin76/boneappleteeth"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/github.svg" alt="Github Logo" width={40} height={40} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
